// Single source of truth for site copy.
// Mirrors the canonical bio in positioning-brief.md — keep the two in sync.

export const SITE = {
  name: 'Moaaz Magdy',
  title: 'Moaaz Magdy',
  description:
    'A little curiosity goes a long way. Explore my projects, experiments, and notes. Say hi to Lulu along the way.',
  role: 'Data & Business Analyst',
  location: 'Cairo, Egypt',
  email: 'moaz.magdy220@gmail.com',
  links: {
    github: 'https://github.com/MMS-21',
    linkedin: 'https://www.linkedin.com/in/moaaz-magdy',
    kaggle: 'https://www.kaggle.com/moaazmagdy',
  },
};

/** Short bio used in the hero and meta tags. */
export const BIO_LEAD = 'I turn customer data into clearer business decisions.';
export const BIO_DETAIL =
  'Who to retain, where value sits, and what to investigate next. ' +
  'I also build AI tools that make analysis repeatable and easier to verify.';
export const BIO_SHORT = `${BIO_LEAD} ${BIO_DETAIL}`;

export const BIO_LONG = [
  'I am a Data & Business Analyst based in Cairo, Egypt. My work sits at the intersection of customer analytics and AI tooling.',
  'On the analytics side I build end-to-end pipelines — RFM segmentation, probabilistic Customer Lifetime Value modelling, churn prediction — that turn raw transactions into retention targets a business can act on.',
  'On the tooling side I build AI applications that do that work automatically. analytics-agent is a pure-Python agent with a hand-rolled tool-calling loop and a quality gate that validates every report before it is written. ai-tell is a desktop app for document authorship provenance.',
  'I care about the unglamorous parts: tests that run without an API key, prompts derived from the data rather than hardcoded, and output that is validated rather than assumed correct.',
];

export interface Project {
  slug: string;
  name: string;
  tagline: string;
  problem: string;
  approach: string[];
  result: string;
  stack: string[];
  repo: string;
  featured: boolean;
  status?: string;
}

export const PROJECTS: Project[] = [
  {
    slug: 'hr-attrition-analysis',
    name: 'Employee Attrition Analysis',
    tagline: 'Exploring employee attrition across roles, overtime, and experience, and turning the findings into a practical retention briefing.',
    problem: 'An overall attrition average hides differences between employee groups. Where should HR investigate first?',
    approach: ['Prepared a star schema for Power BI reporting.', 'Used Python, pandas, and DuckDB to group experience levels and query department and role patterns.', 'Built DAX measures and translated findings into proposed retention actions.'],
    result: 'An inspectable reporting workflow and retention briefing, supported by checked segment comparisons.',
    stack: ['Power BI', 'DAX', 'SQL', 'Python', 'pandas', 'DuckDB'],
    repo: 'https://github.com/MMS-21/hr-attrition-analysis',
    featured: true,
  },
  {
    slug: 'analytics-agent',
    name: 'analytics-agent',
    tagline: 'A pure-Python analytics agent with a hand-rolled tool loop and a report quality gate',
    problem:
      'Asking a business question of a dataset should produce a report with numbers, a chart, and a recommendation. Instead it usually produces a paragraph of confident prose that nobody can verify.',
    approach: [
      'A tool layer of 13 deterministic functions over a DataFrame. No model in the call path, which is what makes the whole suite testable offline.',
      'An agent loop of about 40 lines: parse the model\'s action, execute one tool, feed the result back, repeat. No LangChain, no LangGraph, no dspy.',
      'A parser that handles prose around JSON, nested braces, and the XML tool-call format some providers emit.',
      'A quality gate in front of the final output. A report is rejected unless it has a chart with a description, an Executive Summary, Findings, and Recommendations — and the specific failures are fed back for revision.',
    ],
    result:
      '2,800 lines across 7 files, 21 tests passing with no API key, and a report that cannot be written without passing validation. Over 6 tool calls the agent is told to use what it has rather than thrash.',
    stack: ['Python', 'pandas', 'matplotlib', 'python-docx', 'pytest'],
    repo: 'https://github.com/MMS-21/analytics-agent',
    featured: true,
  },
  {
    slug: 'ai-tell',
    name: 'ai-tell',
    tagline: 'A desktop app that audits documents for authorship provenance',
    problem:
      'Text written by a person and text generated by a model look similar on the page. Stylometric signals differ, but checking them by hand means reading every draft against a guess.',
    approach: [
      'Stylometric analysis — sentence length variance, punctuation habits, function-word distribution — surfaced as readable signals rather than a single opaque score.',
      'Checks for hidden Unicode characters and leftover document metadata that survive copy-paste.',
      'An Electron shell with a React UI over a compiled FastAPI backend.',
      'A documented security model and a GitHub Actions pipeline that builds and publishes a signed Windows installer.',
    ],
    result:
      'A 112 MB Windows installer shipped through an automated release pipeline, with the analysis engine packaged as a compiled binary rather than exposed source.',
    stack: ['Electron', 'React', 'TypeScript', 'FastAPI', 'Python', 'GitHub Actions'],
    repo: 'https://github.com/MMS-21/ai-tell',
    featured: true,
  },
  {
    slug: 'ecommerce-clv-churn',
    name: 'ecommerce-clv-churn',
    tagline: 'RFM segmentation → probabilistic CLV → churn risk, ending in a list you can act on',
    problem:
      'A customer base is not one number. "We have 5,720 customers" tells you nothing about which ones are worth retaining, or which are about to leave.',
    approach: [
      'RFM segmentation to group customers by recency, frequency, and monetary value.',
      'Probabilistic CLV using the BG/NBD and Gamma-Gamma models rather than a single average purchase value.',
      'Churn risk classification layered on top so the segments carry a probability, not just a label.',
      'Export-ready output: ranked at-risk customer lists rather than a chart nobody can action.',
    ],
    result:
      'A pipeline that identifies which segments concentrate revenue at risk, and which customers inside them to contact first.',
    stack: ['Python', 'pandas', 'scikit-learn', 'BG/NBD', 'Gamma-Gamma'],
    repo: 'https://github.com/MMS-21/ecommerce-clv-churn',
    featured: true,
  },
  {
    slug: 'ab-test',
    name: 'A-B-test',
    tagline: 'A/B testing with the statistics written out',
    problem:
      'Most A/B test write-ups stop at "B converted better". That is not a result, it is a coincidence waiting for someone to point it out.',
    approach: [
      'Two-proportion z-test with confidence intervals on the difference.',
      'An explicit hypothesis framework so the test is decided before the data is looked at.',
      'Input validation and sample-size sanity checks.',
    ],
    result: 'A framework for deciding whether a difference is real, and at what confidence.',
    stack: ['Python', 'NumPy', 'SciPy', 'statistics'],
    repo: 'https://github.com/MMS-21/A-B-test',
    featured: false,
  },
  {
    slug: 'analytics-projects',
    name: 'Analytics-Projects',
    tagline: 'Power BI and Tableau dashboards',
    problem: 'Analysis that stops in a notebook is not available to the people who need it.',
    approach: [
      'Power BI dashboards for retail and manufacturing datasets (MelodyMart, Plant Co.).',
      'Tableau work on King County housing data.',
    ],
    result: 'Analytical output packaged for stakeholders who do not open Python.',
    stack: ['Power BI', 'Tableau', 'SQL', 'Python'],
    repo: 'https://github.com/MMS-21/Analytics-Projects',
    featured: false,
  },
  {
    slug: 'sql-for-business-analytics',
    name: 'SQL-for-Business-Analytics',
    tagline: 'SQL against Chinook, COVID-19, and Nashville housing',
    problem: 'Query fluency only shows up on messy, realistic data.',
    approach: [
      'Multi-table joins and window functions on the Chinook database.',
      'Exploratory analysis on COVID-19 case data.',
      'Data cleaning and reshaping of the Nashville housing dataset.',
    ],
    result: 'Query fluency on data that does not arrive clean and tidy.',
    stack: ['SQL', 'SQLite', 'PostgreSQL'],
    repo: 'https://github.com/MMS-21/SQL-for-Business-Analytics',
    featured: false,
  },
];

export const FEATURED = PROJECTS.filter((p) => p.featured);
